### ISSUE TITLE
PosiDeLabVv3 TysFouth-Fouth-Fas-FasMaskrCNN和TysSouth-DeLIPAB RESNET

### ISSUE THREAD

**Issue by ytgcljj** [NanqingD/DeepLabV3-Tensorflow#26]
(dompamine-env) test@test:~/DeepLabV3-Tensorflow$ python3 train_voc12.py 
Traceback (most recent call last):
  File "train_voc12.py", line 17, in <module>
    from libs.datasets.dataset_factory import read_data
  File "/home/test/DeepLabV3-Tensorflow/libs/datasets/dataset_factory.py", line 4, in <module>
    import tensorflow.contrib.slim as slim
ImportError: No module named 'tensorflow.contrib'

**Comment by ytgcljj** [comment]
install DeepLabV3-Tensorflow Need to install first FastMaskRCNN and tensorflow-deeplab-resnet?
